<?php

$menus = [
    'dashboard_admin' => [
        'label' => 'Dashboard Admin',
        'group' => 'Dashboard',
    ],
    'central_monitor' => [
        'label' => 'Monitor Terpusat',
        'group' => 'Dashboard',
    ],
    'dashboard_karyawan' => [
        'label' => 'Dashboard Karyawan',
        'group' => 'Dashboard',
    ],
    'data_karyawan' => [
        'label' => 'Data Karyawan',
        'group' => 'Data Master',
    ],
    'cv_maker_compare' => [
        'label' => 'Compare CV Maker',
        'group' => 'Data Master',
    ],
    'employee_movement' => [
        'label' => 'Perubahan posisi',
        'group' => 'Data Master',
    ],
    'organization_structure' => [
        'label' => 'Struktur Organisasi',
        'group' => 'Operasional',
    ],
    'data_user' => [
        'label' => 'Data User',
        'group' => 'Data Master',
    ],
    'slip_gaji_admin' => [
        'label' => 'Slip Gaji Admin',
        'group' => 'Data Master',
    ],
    'electronic_contract_admin' => [
        'label' => 'Kontrak Elektronik Admin',
        'group' => 'Data Master',
    ],
    'electronic_contract_first_party_signature' => [
        'label' => 'Tanda Tangan Pihak Pertama',
        'group' => 'Data Master',
    ],
    'contract_renewal' => [
        'label' => 'Perpanjangan Kontrak',
        'group' => 'Approval',
    ],
    'resign' => [
        'label' => 'Resign',
        'group' => 'Data Master',
    ],
    'surat_peringatan' => [
        'label' => 'Pelanggaran',
        'group' => 'Data Master',
    ],
    'data_presensi' => [
        'label' => 'Data Presensi',
        'group' => 'Data Master',
    ],
    'attendance_anomaly' => [
        'label' => 'Anomali Presensi',
        'group' => 'Data Master',
    ],
    'attendance_period_lock' => [
        'label' => 'Closing Presensi',
        'group' => 'Operasional',
    ],
    'distribusi_wilayah' => [
        'label' => 'Distribusi Wilayah',
        'group' => 'Data Master',
    ],
    'slip_gaji_user' => [
        'label' => 'Slip Gaji Karyawan',
        'group' => 'Self Service',
    ],
    'electronic_contract_user' => [
        'label' => 'Kontrak Elektronik',
        'group' => 'Self Service',
    ],
    'cuti' => [
        'label' => 'Cuti Tahunan',
        'group' => 'Self Service',
    ],
    'roster' => [
        'label' => 'Cuti Roster',
        'group' => 'Self Service',
    ],
    'off_roster' => [
        'label' => 'Pengajuan OFF Roster',
        'group' => 'Self Service',
    ],
    'izin' => [
        'label' => 'Izin (Paid & Unpaid)',
        'group' => 'Self Service',
    ],
    'presensi' => [
        'label' => 'Presensi Karyawan',
        'group' => 'Self Service',
    ],
    'attendance_correction' => [
        'label' => 'Koreksi Presensi',
        'group' => 'Self Service',
    ],
    'approval_hod' => [
        'label' => 'Approval HOD',
        'group' => 'Approval',
    ],
    'approval_hr' => [
        'label' => 'Approval HR',
        'group' => 'Approval',
    ],
    'approval_sla' => [
        'label' => 'SLA Approval',
        'group' => 'Approval',
    ],
    'setting_hari_off' => [
        'label' => 'Setting Hari Off',
        'group' => 'Operasional',
    ],
    'master_tanggal_merah' => [
        'label' => 'Master Tanggal Merah',
        'group' => 'Operasional',
    ],
    'jadwal_kerja' => [
        'label' => 'Master Jadwal Kerja',
        'group' => 'Operasional',
    ],
    'master_shift' => [
        'label' => 'Master Shift',
        'group' => 'Operasional',
    ],
    'pengaturan_shift' => [
        'label' => 'Pengaturan Shift',
        'group' => 'Operasional',
    ],
    'lembur' => [
        'label' => 'Perintah Lembur',
        'group' => 'Self Service',
    ],
    'perusahaan' => [
        'label' => 'Perusahaan & Organisasi',
        'group' => 'Operasional',
    ],
    'leave_balance' => [
        'label' => 'Saldo Cuti',
        'group' => 'Operasional',
    ],
    'setting_lokasi_presensi' => [
        'label' => 'Lokasi Presensi',
        'group' => 'Admin Panel',
    ],
    'setting_role' => [
        'label' => 'Peran dan Akses',
        'group' => 'Admin Panel',
    ],
    'audit_trail' => [
        'label' => 'Audit Trail',
        'group' => 'Admin Panel',
    ],
    'import_history' => [
        'label' => 'History Import',
        'group' => 'Admin Panel',
    ],
    'exit_portal' => [
        'label' => 'Exit Portal',
        'group' => 'Admin Panel',
    ],
];

return [
    'approval_sidebar_cache_ttl' => env('APPROVAL_SIDEBAR_CACHE_TTL', 30),

    'roles' => [
        'Super Admin' => [
            'aliases' => ['Administrator'],
            'scope_label' => 'Semua data',
            'description' => 'Akses penuh ke seluruh menu, data, dan pengaturan aplikasi.',
        ],
        'HR' => [
            'aliases' => [],
            'scope_label' => 'Semua data karyawan',
            'description' => 'Mengelola data kepegawaian, approval HR, dan operasional HR.',
        ],
        'HOD' => [
            'aliases' => [],
            'scope_label' => 'Beberapa departemen/divisi',
            'description' => 'Mengakses self service dan mereview data karyawan pada satu atau beberapa departemen/divisi yang ditugaskan.',
        ],
        'Manager' => [
            'aliases' => [],
            'scope_label' => 'Departemen yang sama',
            'description' => 'Mengakses data karyawan sesuai departemen pemilik akun.',
        ],
        'Supervisor' => [
            'aliases' => [],
            'scope_label' => 'Divisi yang sama',
            'description' => 'Mengakses data karyawan sesuai divisi pemilik akun.',
        ],
        'Staff' => [
            'aliases' => ['User'],
            'scope_label' => 'Akun sendiri',
            'description' => 'Akses self service untuk kebutuhan karyawan.',
        ],
        'Staff Roster' => [
            'aliases' => ['User Roster'],
            'scope_label' => 'Akun sendiri',
            'description' => 'Akses self service untuk kebutuhan karyawan.',
        ],
        'Admin Divisi' => [
            'aliases' => [],
            'scope_label' => 'Divisi yang ditugaskan',
            'description' => 'Mengelola kebutuhan operasional sesuai satu atau beberapa divisi yang ditugaskan.',
        ],
    ],
    'menus' => $menus,
    'default_menu_permissions' => [
        'Super Admin' => array_keys($menus),
        'HR' => [
            'dashboard_admin',
            'central_monitor',
            'data_karyawan',
            'cv_maker_compare',
            'employee_movement',
            'data_user',
            'electronic_contract_admin',
            'electronic_contract_first_party_signature',
            'contract_renewal',
            'electronic_contract_user',
            'resign',
            'surat_peringatan',
            'data_presensi',
            'attendance_anomaly',
            'attendance_period_lock',
            'distribusi_wilayah',
            'approval_hod',
            'approval_hr',
            'approval_sla',
            'setting_hari_off',
            'master_tanggal_merah',
            'jadwal_kerja',
            'master_shift',
            'pengaturan_shift',
            'lembur',
            'perusahaan',
            'organization_structure',
            'leave_balance',
            'audit_trail',
            'import_history',
        ],
        'HOD' => [
            'dashboard_karyawan',
            'data_karyawan',
            'cv_maker_compare',
            'employee_movement',
            'slip_gaji_user',
            'electronic_contract_user',
            'contract_renewal',
            'cuti',
            'izin',
            'presensi',
            'attendance_correction',
            'approval_hod',
            'setting_hari_off',
            'jadwal_kerja',
            'master_shift',
            'pengaturan_shift',
            'lembur',
            'organization_structure',
        ],
        'Manager' => [
            'dashboard_karyawan',
            'data_karyawan',
            'cv_maker_compare',
            'slip_gaji_user',
            'electronic_contract_user',
            'cuti',
            'izin',
            'presensi',
            'attendance_correction',
            'lembur',
            'organization_structure',
        ],
        'Supervisor' => [
            'dashboard_karyawan',
            'data_karyawan',
            'cv_maker_compare',
            'slip_gaji_user',
            'electronic_contract_user',
            'cuti',
            'izin',
            'presensi',
            'attendance_correction',
            'lembur',
            'organization_structure',
        ],
        'Staff' => [
            'dashboard_karyawan',
            'slip_gaji_user',
            'electronic_contract_user',
            'cuti',
            'izin',
            'presensi',
            'attendance_correction',
            'lembur',
        ],
        'Staff Roster' => [
            'dashboard_karyawan',
            'slip_gaji_user',
            'electronic_contract_user',
            'cuti',
            'roster',
            'off_roster',
            'izin',
            'presensi',
            'attendance_correction',
            'lembur',
        ],
        'Admin Divisi' => [
            'dashboard_karyawan',
            'data_karyawan',
            'cv_maker_compare',
            'slip_gaji_user',
            'electronic_contract_user',
            'contract_renewal',
            'cuti',
            'izin',
            'presensi',
            'attendance_correction',
            'setting_hari_off',
            'jadwal_kerja',
            'master_shift',
            'pengaturan_shift',
            'lembur',
            'organization_structure',
        ],
    ],
];
